### ISSUE TITLE
How to stop the "Using cache"

### ISSUE THREAD

**Issue by Zerounary** [duck8823/duci#355]
I try to create a [duci-simple-demo](https://github.com/Zerounary/duci-simple-demo) project.  I coded in Windows VSCode and pushed the go-project to github in order to deploy the building-result to another centos7 server.

but, sometimes cause of "Using cache", It's not work.

**Comment by Zerounary** [comment]
The CI Server is Using Docker.  Run with this

```shell
docker run -p 8080:8080 -e GITHUB_API_TOKEN=xxx -v /var/run/docker.sock:/var/run/docker.sock duck8823/duci
```

**Comment by Zerounary** [comment]
![image](https://user-images.githubusercontent.com/31512287/100056873-59e7c900-2e61-11eb-8982-6502c44bcc96.png)

**Comment by duck8823** [comment]
Sorry, there is currently no way around the cache.
I recommend using Dockerfile only to define the execution environment (e.g. installation of the necessary tools), and use a task runner such as Makefile.

**Comment by Zerounary** [comment]
Thanks for your replies and suggestions. 

After I created a linux-crontab to remove the <none> docker-image,  the caching problem is solved. If I have time later, I will write a duci project document to help everyone use duci  in their projects more conveniently.

Thanks again : )
